title: My Jupyter Book
author: Hiba Bederina
logo: null

repository:
  url: https://github.com/Hiba-Bdr/Docs
  path_to_book: ""
  branch: main

only_build_toc_files: true

execute:
  execute_notebooks: "off"

html:
  favicon: null
  home_page_in_navbar: true
  use_repository_button: true
  use_edit_page_button: false
  use_issues_button: false
